Generator pre-training...
Step 0/250000
----------
Traceback (most recent call last):
  File "main.py", line 203, in <module>
    lr=lr_pre, patch_size=patch_size)
  File "/raven/u/lumah/code/E6040-super-resolution-project/training_pre.py", line 87, in training_pre
    sr_patches = model(lr_patches)
  File "/mpcdf/soft/SLE_15/packages/skylake/pytorch/gpu-cuda-11.2/anaconda_3_2020.02-2020.02/1.8.1/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/raven/u/lumah/code/E6040-super-resolution-project/ecbm6040/model/mDCSRN_WGAN.py", line 106, in forward
    out = self.block3(out)
  File "/mpcdf/soft/SLE_15/packages/skylake/pytorch/gpu-cuda-11.2/anaconda_3_2020.02-2020.02/1.8.1/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/mpcdf/soft/SLE_15/packages/skylake/pytorch/gpu-cuda-11.2/anaconda_3_2020.02-2020.02/1.8.1/lib/python3.7/site-packages/torch/nn/modules/container.py", line 119, in forward
    input = module(input)
  File "/mpcdf/soft/SLE_15/packages/skylake/pytorch/gpu-cuda-11.2/anaconda_3_2020.02-2020.02/1.8.1/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/raven/u/lumah/code/E6040-super-resolution-project/ecbm6040/model/mDCSRN_WGAN.py", line 24, in forward
    return torch.cat([x, new_features], 1)
RuntimeError: CUDA out of memory. Tried to allocate 1.25 GiB (GPU 0; 39.59 GiB total capacity; 36.40 GiB already allocated; 829.69 MiB free; 36.92 GiB reserved in total by PyTorch)